version: "3.5"

services:
  db_test:
    image: postgres:12.3
    container_name: test-gin-templates_db_test
    environment:
      - POSTGRES_DB=test-gin-templates_test
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5433:5432"
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5

  test:
    build:
      context: .
    container_name: test-gin-templates_test
    command: ./bin/test.sh
    depends_on:
      db_test:
        condition: service_healthy
