app_name = "test-gin-templates"
app_port = "8080"
db_host = "0.0.0.0"
db_password = "postgres"
db_username = "postgres"


[debug]
db_name = "test-gin-templates_development"
db_port = "5432"

[test]
db_name = "test-gin-templates_test"
db_port = "5433"
