name: Integration test
on: push

jobs:
  integ_test:
    name: "Integration test"
    runs-on: ubuntu-latest
    environment:
      name: Test Integration
    env:
      TEST: ${{ secrets.TEST }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo ENV
        run: echo $TEST
